### ISSUE TITLE
Export Error

### ISSUE THREAD

**Issue by akahomebody** [wonderunit/storyboarder#1316]
I'm getting these error's when trying to export my 16 board scene to video:

"Could not export. An error occured."

"Error: Could not use ffmpeg. Failed with error 1"

All other Storyboarder files I've tried are working fine.

**Comment by audionerd** [comment]
Do any of the boards have audio?

**Comment by akahomebody** [comment]
The first board did. I just removed it to see if it would render, but it still failed, showing the same errors.

**Comment by audionerd** [comment]
Can you send us a ZIP of the entire Storyboarder project? We can take a look.

**Comment by akahomebody** [comment]
Sweet, thanks!

[Flinch_MFAT_GlobalWarming_Storyboard_V3_02.zip](https://github.com/wonderunit/storyboarder/files/2288388/Flinch_MFAT_GlobalWarming_Storyboard_V3_02.zip)

**Comment by audionerd** [comment]
Hmm, that's odd. I was able to export a video with no errors.

[Flinch_MFAT_GlobalWarming_Storyboard_V3_02 Exported 2018-08-14 04.40.23.zip](https://github.com/wonderunit/storyboarder/files/2288612/Flinch_MFAT_GlobalWarming_Storyboard_V3_02.Exported.2018-08-14.04.40.23.zip)

Could you try again, and open the Developer Tools (`View > Toggle Developer Tools`) and let us know what you see there while trying to export? There should be a log similar to the error (e.g.: "Error: Could not use ffmpeg. Failed with error 1") and some context above explaining why. A screenshot or two should be helpful.

**Comment by audionerd** [comment]
Is this on a Mac or PC?

**Comment by akahomebody** [comment]
This is what I get inside of the console.

![1](https://user-images.githubusercontent.com/42361712/44120535-c4369f9c-a070-11e8-992a-baeba92500f0.png)
![2](https://user-images.githubusercontent.com/42361712/44120536-c46b19a2-a070-11e8-82d7-544fc66c2b9c.png)

**Comment by audionerd** [comment]
OK thanks. That is helpful. 

The "No such file or directory" problem is the bug.

I think something in Storyboarder's code is causing it to either have problems with files on windows with spaces in their names, or possibly with long directory names, or possibly across drives (C vs E).

You could try making a copy in C: with a shorter folder and try exporting that?

I'll mark this as a bug.

**Comment by akahomebody** [comment]
Nice! Worked a charm. Thanks for the quick responses! App is 11/10.

Just while I'm here, do you have any intentions on porting it to ipad? Would be amazing to have a good, portable storyboarding app.

**Comment by audionerd** [comment]
Glad to help! Do you know if the problem was C vs E drive? or just the long directory name?

Re: iPad, we've been working on an iPad version in-house, but nothing released yet. Thanks for the feedback.

**Comment by audionerd** [comment]
Thanks. Good to know!

**Comment by setpixel** [comment]
Could be spaces in paths. I had this problem on script assistant.

**Comment by audionerd** [comment]
I wonder if the unicode characters Στέλιος are causing the problem?

**Comment by Kjghltrtszg** [comment]
Wow you're fast :) I thought of that too and then tried from the root of my second drive only to fail again. The software must be trying to write or read something on my user folder no matter where the files are, you think i have to change the username to latin characters to get it to work?

**Comment by sbilochenko** [comment]
Hello there! I have a similar problem with export video, Here a part of the log:

C:\Storyboarder\resources\app.asar\node_modules\electron-log\lib\transports\console.js:72 23:21:43.512 › Error: spawn C:\Storyboarder\resources\app.asar\node_modules\@ffmpeg-installer\win32-x64\ffmpeg.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

My system is Win 10 64 Bit

**Comment by audionerd** [comment]
@sbilochenko That looks like a different issue, https://github.com/wonderunit/storyboarder/issues/2107, which will be fixed in the next release.

**Comment by liz0920** [comment]
I'm also having issues exporting to video. I tried deleting the audios and it still doesn't let me export. 

23:22:18.526 › UnhandledRejection EncodingError: Unable to decode audio data
    at onRejection (C:\Program Files\Storyboarder\resources\app.asar\node_modules\electron-log\src\catchErrors.js:57:18)
    at onRendererRejection (C:\Program Files\Storyboarder\resources\app.asar\node_modules\electron-log\src\catchErrors.js:77:5)
23:22:18.527 › UnhandledRejection: "Tone.Buffer: could not decode audio data: D:\\FileHistory\\BACKUP 2020-10-28\\HP PAVILLION 2020\\DOCUMENTS\\URL\\4° INTERCICLO\\ANIMACIÓN\\SB\\images\\9XRGY-Chips bag Sound effect-[AudioTrimmer.com].mp3"
    at onRejection (C:\Program Files\Storyboarder\resources\app.asar\node_modules\electron-log\src\catchErrors.js:65:17)
    at onRendererRejection (C:\Program Files\Storyboarder\resources\app.asar\node_modules\electron-log\src\catchErrors.js:77:5)

DevTools failed to load SourceMap: Could not parse content for file:///C:/Program%20Files/Storyboarder/resources/app.asar/src/index.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///C:/Program%20Files/Storyboarder/resources/app.asar/src/Point.js.map: Unexpected end of JSON input

calling ffmpeg with args (31) ["-safe", "0", "-i", "C:\Users\Usuario\AppData\Local\Temp\tmp-1656BvSDTE2VQBmA\video.ffconcat", "-i", "C:\Users\Usuario\AppData\Local\Temp\tmp-1656BvSDTE2VQBmA\watermark.png", "-i", "D:\FileHistory\BACKUP 2020-10-28\HP PAVILLION 2020…RGY-Chips bag Sound effect-[AudioTrimmer.com].mp3", "-filter_complex", "[0]scale=-2:900[frame];[1]scale=-2:'min(225,ih)':f…, areverse,adelay=18750|18750[s2];[s2]amix=1[mix]", "-map", "[vid]:v", "-r", 24, "-vcodec", "libx264", "-acodec", "aac", "-pix_fmt", "yuv420p", "-tune", "stillimage", "-preset", "veryslow", "-map", "[mix]:a", "-movflags", "+faststart", "-n", "-stats", "D:\FileHistory\BACKUP 2020-10-28\HP PAVILLION 2020…ÓN\SB\exports\SB Exported 2022-06-21 11.23.05.mp4"]


23:23:06.753 › Error: Could not use ffmpeg. Failed with error 1
    at ChildProcess.<anonymous> (C:\Program Files\Storyboarder\resources\app.asar\src\js\exporters\ffmpeg.js:85)
    at ChildProcess.emit (events.js:327)
    at ChildProcess.cp.emit (C:\Program Files\Storyboarder\resources\app.asar\node_modules\cross-spawn\lib\enoent.js:40)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275)
setTimeout (async)
consoleLog @ C:\Program Files\Storyboarder\resources\app.asar\node_modules\electron-log\src\transports\console.js:93
transport @ C:\Program Files\Storyboarder\resources\app.asar\node_modules\electron-log\src\transports\console.js:46
runTransport @ C:\Program Files\Storyboarder\resources\app.asar\node_modules\electron-log\src\log.js:44
runTransports @ C:\Program Files\Storyboarder\resources\app.asar\node_modules\electron-log\src\log.js:27
log @ C:\Program Files\Storyboarder\resources\app.asar\node_modules\electron-log\src\log.js:21
exportVideo @ C:\Program Files\Storyboarder\resources\app.asar\src\js\window\main-window.js:5674


calling ffmpeg with args (31) ["-safe", "0", "-i", "C:\Users\Usuario\AppData\Local\Temp\tmp-16562NIjnepMjL4D\video.ffconcat", "-i", "C:\Users\Usuario\AppData\Local\Temp\tmp-16562NIjnepMjL4D\watermark.png", "-i", "D:\FileHistory\BACKUP 2020-10-28\HP PAVILLION 2020…RGY-Chips bag Sound effect-[AudioTrimmer.com].mp3", "-filter_complex", "[0]scale=-2:900[frame];[1]scale=-2:'min(225,ih)':f…, areverse,adelay=18750|18750[s2];[s2]amix=1[mix]", "-map", "[vid]:v", "-r", 24, "-vcodec", "libx264", "-acodec", "aac", "-pix_fmt", "yuv420p", "-tune", "stillimage", "-preset", "veryslow", "-map", "[mix]:a", "-movflags", "+faststart", "-n", "-stats", "D:\FileHistory\BACKUP 2020-10-28\HP PAVILLION 2020…ÓN\SB\exports\SB Exported 2022-06-21 11.27.43.mp4"]0: "-safe"1: "0"2: "-i"3: "C:\Users\Usuario\AppData\Local\Temp\tmp-16562NIjnepMjL4D\video.ffconcat"4: "-i"5: "C:\Users\Usuario\AppData\Local\Temp\tmp-16562NIjnepMjL4D\watermark.png"6: "-i"7: "D:\FileHistory\BACKUP 2020-10-28\HP PAVILLION 2020\DOCUMENTS\URL\4° INTERCICLO\ANIMACIÓN\SB\images\9XRGY-Chips bag Sound effect-[AudioTrimmer.com].mp3"8: "-filter_complex"9: "[0]scale=-2:900[frame];[1]scale=-2:'min(225,ih)':force_original_aspect_ratio=decrease[watermark];[frame][watermark]overlay=W-w:H-h[vid];[2]areverse, afade=d=0.25:curve=exp, areverse,adelay=18750|18750[s2];[s2]amix=1[mix]"10: "-map"11: "[vid]:v"12: "-r"13: 2414: "-vcodec"15: "libx264"16: "-acodec"17: "aac"18: "-pix_fmt"19: "yuv420p"20: "-tune"21: "stillimage"22: "-preset"23: "veryslow"24: "-map"25: "[mix]:a"26: "-movflags"27: "+faststart"28: "-n"29: "-stats"30: "D:\FileHistory\BACKUP 2020-10-28\HP PAVILLION 2020\DOCUMENTS\URL\4° INTERCICLO\ANIMACIÓN\SB\exports\SB Exported 2022-06-21 11.27.43.mp4"length: 31__proto__: Array(0)

23:30:32.955 › Error: Could not use ffmpeg. Failed with error 1
    at ChildProcess.<anonymous> (C:\Program Files\Storyboarder\resources\app.asar\src\js\exporters\ffmpeg.js:85)
    at ChildProcess.emit (events.js:327)
    at ChildProcess.cp.emit (C:\Program Files\Storyboarder\resources\app.asar\node_modules\cross-spawn\lib\enoent.js:40)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275)
setTimeout (async)
consoleLog @ C:\Program Files\Storyboarder\resources\app.asar\node_modules\electron-log\src\transports\console.js:93
transport @ C:\Program Files\Storyboarder\resources\app.asar\node_modules\electron-log\src\transports\console.js:46
runTransport @ C:\Program Files\Storyboarder\resources\app.asar\node_modules\electron-log\src\log.js:44
runTransports @ C:\Program Files\Storyboarder\resources\app.asar\node_modules\electron-log\src\log.js:27
log @ C:\Program Files\Storyboarder\resources\app.asar\node_modules\electron-log\src\log.js:21
exportVideo @ C:\Program Files\Storyboarder\resources\app.asar\src\js\window\main-window.js:5674
async function (async)
exportVideo @ C:\Program Files\Storyboarder\resources\app.asar\src\js\window\main-window.js:5660
(anonymous) @ C:\Program Files\Storyboarder\resources\app.asar\src\js\window\main-window.js:6903
emit @ events.js:315
onMessage @ electron/js2c/renderer_init.js:91

**Comment by RoundHog** [comment]
Hello,

I'm having the same issue, even with a short folder name (without spaces).
My OS is Windows 10 Family 22H2.

The log shows many "DevTools failed to parse SourceMap" errors followed by ".map" file names in file:///C:/Program%20Files/Storyboarder/, then ends with the following block :

Error: spawn C:\Program Files\Storyboarder\resources\app.asar\node_modules\@ffmpeg-installer\win32-x64\ffmpeg.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
