### ISSUE TITLE
Shot Generator IK: some custom model files cause character errors

### ISSUE THREAD

**Issue by audionerd** [wonderunit/storyboarder#1713]
Using `snake.glb` causes a fatal error.

https://github.com/wonderunit/shot-generator-models/tree/master/characters/custom/snake

**Comment by VladStepura** [comment]
About that, the current state of ragdoll(ik class) is designed specifically for the built-in character models. For now, i can disable ik for custom models, so there will be no error. And start working on custom models ik cause at current state ik is a little bit wonky and it needs to be set up for specific model to work correctly.

**Comment by josephbburg** [comment]
This is what I get when I try to import a .glb created with Blender 2.8:

TypeError: Cannot read property 'dispose' of null
    at Ragdoll.removeFromScene (D:\git-storyboarder\storyboarder\src\js\shot-generator\IK\objects\IkObjects\Ragdoll.js:167:38)
    at doCleanup (D:\git-storyboarder\storyboarder\src\js\shot-generator\Character.js:202:23)
    at cleanup (D:\git-storyboarder\storyboarder\src\js\shot-generator\Character.js:332:7)
    at HTMLUnknownElement.callCallback (D:\git-storyboarder\storyboarder\node_modules\react-dom\cjs\react-dom.development.js:149:14)
    at Object.invokeGuardedCallbackDev (D:\git-storyboarder\storyboarder\node_modules\react-dom\cjs\react-dom.development.js:199:16)
    at invokeGuardedCallback (D:\git-storyboarder\storyboarder\node_modules\react-dom\cjs\react-dom.development.js:256:31)
    at safelyCallDestroy (D:\git-storyboarder\storyboarder\node_modules\react-dom\cjs\react-dom.development.js:16999:5)
    at commitUnmount (D:\git-storyboarder\storyboarder\node_modules\react-dom\cjs\react-dom.development.js:17336:17)
    at commitNestedUnmounts (D:\git-storyboarder\storyboarder\node_modules\react-dom\cjs\react-dom.development.js:17380:5)
    at unmountHostComponents (D:\git-storyboarder\storyboarder\node_modules\react-dom\cjs\react-dom.development.js:17641:7)


Any known workarounds? Thanks.

**Comment by setpixel** [comment]
Yeah! if you could send us the file, that would be great!

**Comment by josephbburg** [comment]
[brain.zip](https://github.com/wonderunit/storyboarder/files/3393977/brain.zip)
This is the 'naked' version-- no non-deforming bones.
[Brain_.zip](https://github.com/wonderunit/storyboarder/files/3393980/Brain_.zip)
This one has IK setup and maybe a couple of other constraints.

I haven't used this format in the past, so it might be a less than excellent export. I can give you the .blend file, too, if you want. Thanks.

**Comment by setpixel** [comment]
ahh - cool i'll check it out.

just so you know, a blender ik setup will not work in storyboarder, and will probably never. 

the only thing that will will is manual bone rotations.

**Comment by setpixel** [comment]
cool brain btw... reminds me of rick and morty

**Comment by josephbburg** [comment]
OK. I assumed the ragdoll-IK in Shot Builder was IK in the gltf. It seems like the simple way to do things on the DCC end. Maybe Storyboarder could translate that to its own ragdoll system on import?

Anyways, thanks! I'm doing a scientific illustration/animation for an engineer right now. He has an idea about using a particular "brain wave" to control devices. I think the character will make the illustration more appealing.

**Comment by josephbburg** [comment]
Here's the .blend:
[Brain_friend.000.blend.zip](https://github.com/wonderunit/storyboarder/files/3394200/Brain_friend.000.blend.zip)

**Comment by audionerd** [comment]
We’re going to prevent custom models from using IK for now.

Fixed by https://github.com/wonderunit/storyboarder/commit/8c0c6301813531705cf011a4669296977611e8b0
