### ISSUE TITLE
Doesn't install / installs incorrectly

### ISSUE THREAD

**Issue by michiderp** [wonderunit/storyboarder#1775]
downloading with chrome from the site wonderunit.com/storyboarder and running storyboarder-setup.exe as either a regular user or administrator "installs" v1.13.0 and brings up the "getting started", "open", "create new" menu.  however selecting create new (any board format) opens the application, the ui (the canvas and brushes) flashes briefly and then vanishes. the top menus file, edit, etc , are expandable, but nothing happens if an option is hit ie going to help - found a bug submit an issue, does nothing. 
sometimes creating a new board idles at "loading boardname preparing to display..." for forever.

**To Reproduce**

1. install on windows 10
2. Click on 'create new story board'
3. choose any type
4. the application will load flash the ui and then vanish the ui leaving the upper menu 'file', 'edit' , etc browsable, but ineffective
5. sometimes the application will Not load. and hold at "loading, preparing to display"

**Expected behavior**
the app will load with the ability to use it, 

**Screenshots**
![example1](https://user-images.githubusercontent.com/13645952/64054560-85dca780-cb55-11e9-87e0-b91c1141b381.PNG)
![example2](https://user-images.githubusercontent.com/13645952/64054567-8ecd7900-cb55-11e9-92fb-3556a19c7c50.PNG)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome
 - Version 1.13.0

**Additional context**
i had previously installed this software on this machine a year or so ago, however, this machine has had to be wiped many times and it got a whole new drive, installing a game once brought up a warning "we don't recognize your graphics card". So i don't know if it's just another issue with my particular machine, or if this is a real bug, or if there is some residual ghost causing the issue.

**Comment by audionerd** [comment]
There should be a log file for Storyboarder at

`%USERPROFILE%\AppData\Roaming\Storyboarder\log.log`

Can you take a look and see if any errors are logged?

**Comment by michiderp** [comment]
there were two errors at the top

[2019-08-30 18:08:40.139] [error] Could not read prefs. Loading defaults.
[2019-08-30 18:08:40.140] [error] Error: ENOENT: no such file or directory, open 'C:\Users\-----\AppData\Roaming\Storyboarder\pref.json'
    at Object.openSync (fs.js:453:3)
    at Object.func [as openSync] (electron/js2c/asar.js:155:31)
    at Object.readFileSync (fs.js:353:35)
    at Object.fs.readFileSync (electron/js2c/asar.js:597:40)
    at load (C:\Program Files\Storyboarder\resources\app.asar\src\js\prefs.js:83:34)
    at Object.init (C:\Program Files\Storyboarder\resources\app.asar\src\js\prefs.js:178:3)
    at Object.<anonymous> (C:\Program Files\Storyboarder\resources\app.asar\src\js\main.js:12:12)
    at Module._compile (internal/modules/cjs/loader.js:808:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)

**Comment by audionerd** [comment]
You could try renaming that Storyboarder data folder to something else and see if get gets recreated by Storyboarder with correct data files

**Comment by michiderp** [comment]
I renamed the folder "/AppData/Roaming/Storyboarder" to "/AppData/Roaming/renamed"
and when i started storyboarder up again the same issue occured, "/AppData/Roaming/Storyboarder" was recreated, and the log inside was the same as the what i shared.
I did have to restart my computer because there was a bunch of instances of storyboarder in my task manager which prevented me from renaming the appdata folder.

**Comment by audionerd** [comment]
what are the last lines in the log?

**Comment by michiderp** [comment]
[2019-08-30 19:08:12.858] [info] Loading preferences from C:\Users\ ----\AppData\Roaming\Storyboarder\pref.json
[2019-08-30 19:08:13.270] [info]  BOARD PATH:  C:\Users\ ---  \Documents\t4\t4.storyboarder
[2019-08-30 19:08:13.676] [info] saved posterframe board-1-CJ17C-posterframe.jpg
[2019-08-30 19:08:13.681] [info] saved thumbnail board-1-CJ17C-thumbnail.png at index: 0
[2019-08-30 19:08:13.747] [info] updateSketchPaneBoard
[2019-08-30 19:08:13.748] [info] loadSketchPaneLayers
[2019-08-30 19:08:13.888] [info] loadPosterFrame rendered jpg
[2019-08-30 19:08:13.905] [info] clearPosterFrame

**Comment by audionerd** [comment]
Do you see anything different in the console if you do View > Show Developer Tools? Should be basically the same log.
Odd. Wonder if its a graphics card issue.

**Comment by michiderp** [comment]
i cannot toggle the dev tools
