### ISSUE TITLE
Create blank project not working in version 2.1.0 AppImage

### ISSUE THREAD

**Issue by JORGETECH** [wonderunit/storyboarder#2108]
**Describe the bug**
In the 2.1.0 Linux AppImage version of Storyboarder, creating a blank project from the startup screen just does nothing. Opening a project made using an older version (e.g: 2.0.1) works fine.

**To Reproduce**
1. Go to 'Create New Storyboard...'
2. Click on 'Create a blank...'
3. Select Aspect Ratio (16:9 in my case)
4. Select target folder and name the project
5. The file selector closes and just goes back to the startup screen and no folder project is created

**Expected behavior**
A new project should be created.

**Desktop (please complete the following information):**
 - OS: Linux ((K)Ubuntu 20.04 LTS)
 - Version 2.1.0 (AppImage)

**Comment by audionerd** [comment]
Can you send us the log file?

**Comment by JORGETECH** [comment]
> Can you send us the log file?

Of course, the attached file shows the output of the Terminal when I reproduce the bug.
[error_log.txt](https://github.com/wonderunit/storyboarder/files/5180557/error_log.txt)

**Comment by audionerd** [comment]
Can you also send the Storyboarder log file? You can access it from the help menu.

**Comment by JORGETECH** [comment]
> Can you also send the Storyboarder log file? You can access it from the help menu.

Are you talking about the log.txt file? I opened it and no error message appears, only things about reading the config file and license keys.

**Comment by audionerd** [comment]
Yeah send the log.txt if you have it, it might be useful.

Would you be able to run the project from source to help us test on Linux?

Looks like the problem is here with the save dialog box on Linux: https://github.com/wonderunit/storyboarder/blob/master/src/js/main.js#L851

It's not getting a valid `filePath` for some reason.

**Comment by audionerd** [comment]
What are you using as a project name? Are you adding an extension?

**Comment by ghost** [comment]
Same problem on fedora 37

Launch of the appimage:

```
00:00:00.000  › Loading preferences from /home/USERNAME/.config/Storyboarder/pref.json
00:00:00.000  › Could not read prefs. Loading defaults.
00:00:00.000  › Error: ENOENT: no such file or directory, open '/home/USERNAME/.config/Storyboarder/pref.json'
    at Object.openSync (fs.js:453:3)
    at Object.func [as openSync] (electron/js2c/asar.js:155:31)
    at Object.readFileSync (fs.js:353:35)
    at Object.fs.readFileSync (electron/js2c/asar.js:597:40)
    at load (/tmp/.mount_Storyb6tmFR1/resources/app.asar/src/js/prefs.js:83:34)
    at Object.init (/tmp/.mount_Storyb6tmFR1/resources/app.asar/src/js/prefs.js:178:3)
    at Object.<anonymous> (/tmp/.mount_Storyb6tmFR1/resources/app.asar/src/js/main.js:12:12)
    at Module._compile (internal/modules/cjs/loader.js:839:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:851:10)
    at Module.load (internal/modules/cjs/loader.js:701:32)
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
00:00:00.000  › ffmpeg version N-87327-g18821e3ba1-static
00:00:00.000  › Reading /home/USERNAME/.config/Storyboarder/keymap.json
00:00:00.000 0 › No license key found
00:00:00.000 0 › http://10.0.0.7:1888
00:00:00.000  › Checking for update
00:00:00.000  › auto-updater: checking-for-update
00:00:00.000 › Update for version 2.1.0 is not available (latest version: 2.1.0, downgrade is disallowed).
00:00:00.000 › auto-updater: update-not-available
```


Then this when trying to create a blank project:

```
(node:95083) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
    at Object.mkdirSync (fs.js:770:3)
    at createAndLoadScene (/tmp/.mount_Storyb6tmFR1/resources/app.asar/src/js/main.js:881:6)
(node:95083) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:95083) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.(node:95083) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
    at Object.mkdirSync (fs.js:770:3)
    at createAndLoadScene (/tmp/.mount_Storyb6tmFR1/resources/app.asar/src/js/main.js:881:6)
(node:95083) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:95083) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
