### ISSUE TITLE
EPERM operation not permitted

### ISSUE THREAD

**Issue by TheMidnightLeo** [wonderunit/storyboarder#2194]
**Describe the bug**
Every time I make a new Storyboarder Project or open an existing one, It brings up an error message saying "EPERM: Operation not permitted" (please refer to the screenshot I've provided)

**Expected behavior**
I just want to create a new Storyboarder File and make a new storyboard project in Storyboarder.

**Screenshots**
![Screenshot 2021-01-17 123815](https://user-images.githubusercontent.com/77585978/104852504-fa39f700-58c0-11eb-8925-57e2c2730e5f.png)

Desktop
 - OS: Windows 10 Pro

Any Help with this issue will be greatly appreciated.
Thank You.

**Comment by audionerd** [comment]
You could try a folder that has no spaces in the name. Or try checking that you have write permissions for the folder.

**Comment by TheMidnightLeo** [comment]
I tried renaming the folder, I made sure I unchecked Write Only on the Storyboarder and project file folder.
Still no dice.

**Comment by audionerd** [comment]
Does the Storyboarder log file show any errors?

**Comment by TheMidnightLeo** [comment]
I don't know where the Storyboarder log file is...

**Comment by audionerd** [comment]
```
on Linux: ~/.config/Storyboarder/log.log
on macOS: ~/Library/Logs/Storyboarder/log.log
on Windows: %USERPROFILE%\AppData\Roaming\Storyboarder\log.log
```

**Comment by TheMidnightLeo** [comment]
Thank You.

Here's what I've found in the Log File:
[2021-01-17 16:27:10.129] [info] saved board file: C:\Users\Dell T7500\OneDrive\Pictures\TestStoryboardProject\TestStoryboardProject.storyboarder
[2021-01-17 16:35:24.676] [info] Loading preferences from C:\Users\Dell T7500\AppData\Roaming\Storyboarder\pref.json
[2021-01-17 16:35:25.117] [info] ffmpeg version N-87327-g18821e3
[2021-01-17 16:35:25.118] [info] Reading C:\Users\Dell T7500\AppData\Roaming\Storyboarder\keymap.json
[2021-01-17 16:35:25.136] [info] No license key found
[2021-01-17 16:35:32.310] [info] Checking for update
[2021-01-17 16:35:32.311] [info] auto-updater: checking-for-update
[2021-01-17 16:35:34.287] [info] Update for version 2.0.1 is not available (latest version: 2.0.1, downgrade is disallowed).
[2021-01-17 16:35:34.288] [info] auto-updater: update-not-available
[2021-01-17 16:35:38.067] [info] Loading preferences from C:\Users\Dell T7500\AppData\Roaming\Storyboarder\pref.json
[2021-01-17 16:35:38.303] [info]  BOARD PATH:  C:\Users\Dell T7500\OneDrive\Pictures\TestStoryboardProject\TestStoryboardProject.storyboarder
[2021-01-17 16:35:38.943] [info] saving placeholder board-1-9N0TX-thumbnail.png
[2021-01-17 16:35:43.404] [error] Error: EPERM: operation not permitted, open 'C:\Users\Dell T7500\OneDrive\Pictures\TestStoryboardProject\images\board-1-9N0TX-thumbnail.png'
    at Object.openSync (fs.js:453:3)
    at Object.func [as openSync] (electron/js2c/asar.js:155:31)
    at Object.writeFileSync (fs.js:1246:35)
    at saveDataURLtoFile (C:\Program Files\Storyboarder\resources\app.asar\src\js\window\main-window.js:2305:6)
    at verifyScene (C:\Program Files\Storyboarder\resources\app.asar\src\js\window\main-window.js:691:7)
    at EventEmitter.load (C:\Program Files\Storyboarder\resources\app.asar\src\js\window\main-window.js:278:11)
[2021-01-17 16:35:57.128] [info] Loading preferences from C:\Users\Dell T7500\AppData\Roaming\Storyboarder\pref.json
[2021-01-17 16:35:57.571] [info] ffmpeg version N-87327-g18821e3
[2021-01-17 16:35:57.572] [info] Reading C:\Users\Dell T7500\AppData\Roaming\Storyboarder\keymap.json
[2021-01-17 16:35:57.591] [info] No license key found
[2021-01-17 16:36:05.159] [info] Checking for update
[2021-01-17 16:36:05.159] [info] auto-updater: checking-for-update
[2021-01-17 16:36:07.540] [info] Update for version 2.0.1 is not available (latest version: 2.0.1, downgrade is disallowed).
[2021-01-17 16:36:07.541] [info] auto-updater: update-not-available

**Comment by Piercinghuber** [comment]
Try opening Storyboarder as an administrator, worked for me.

**Comment by TheMidnightLeo** [comment]
> 
> 
> Try opening Storyboarder as an administrator, worked for me.

That actually worked...O_o
