### ISSUE TITLE
Can't export Gltf wit a child character 

### ISSUE THREAD

**Issue by Eriaco** [wonderunit/storyboarder#2220]
[2021-02-16 12:39:39.670] [info] ready!
[2021-02-16 12:39:40.179] [info] Using existing key.pem and cert.pem from /Users/heribertoacosta/Library/Application Support/Storyboarder
[2021-02-16 12:39:40.494] [info] XRServer running at https://192.168.1.9:1234
[2021-02-16 12:39:40.603] [error] UnhandledRejection: {"isTrusted":true}
    at n (/Applications/Storyboarder.app/Contents/Resources/app.asar/src/build/shot-generator.js:367:10779)
    at o (/Applications/Storyboarder.app/Contents/Resources/app.asar/src/build/shot-generator.js:367:10918)
[2021-02-16 12:39:40.603] [error] UnhandledRejection: {"isTrusted":true}
    at n (/Applications/Storyboarder.app/Contents/Resources/app.asar/src/build/shot-generator.js:367:10779)
    at o (/Applications/Storyboarder.app/Contents/Resources/app.asar/src/build/shot-generator.js:367:10918)
[2021-02-16 12:39:40.606] [error] UnhandledRejection: {"isTrusted":true}
    at n (/Applications/Storyboarder.app/Contents/Resources/app.asar/src/build/shot-generator.js:367:10779)
    at o (/Applications/Storyboarder.app/Contents/Resources/app.asar/src/build/shot-generator.js:367:10918)

**Comment by audionerd** [comment]
Marking as a duplicate of #2220
