### ISSUE TITLE
Storyboarder Appimage won't start

### ISSUE THREAD

**Issue by thomasrenkert** [wonderunit/storyboarder#2229]
This is the output in the terminal

```
$ ./Storyboarder-3.0.0-linux-x86_64.AppImage 
13:33:39.890 › Loading preferences from /home/thomas/.config/Storyboarder/pref.json
13:33:39.968 › Could not read prefs. Loading defaults.
13:33:39.968 › Error: ENOENT: no such file or directory, open '/home/thomas/.config/Storyboarder/pref.json'
    at Object.openSync (fs.js:466:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1812)
    at Object.readFileSync (fs.js:368:35)
    at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8583)
    at load (/tmp/.mount_StorybzgHPbm/resources/app.asar/src/js/prefs.js:83:34)
    at Object.init (/tmp/.mount_StorybzgHPbm/resources/app.asar/src/js/prefs.js:178:3)
    at Object.<anonymous> (/tmp/.mount_StorybzgHPbm/resources/app.asar/src/js/main.js:13:12)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
(node:1894288) UnhandledPromiseRejectionWarning: Could not find ffmpeg executable, tried "/tmp/.mount_StorybzgHPbm/resources/app.asar/node_modules/@ffmpeg-installer/linux-x64/ffmpeg" and "/tmp/.mount_StorybzgHPbm/resources/app.asar/node_modules/@ffmpeg-installer/ffmpeg/node_modules/@ffmpeg-installer/linux-x64/ffmpeg"
(node:1894288) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1894288) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by b4zz4** [comment]
`(node:29260) UnhandledPromiseRejectionWarning: Could not find ffmpeg executable,...`

I think the ffmpeg is missing.

**Comment by heavenlypete** [comment]
I have a similar issue on 5.11.2-1-MANJARO

>$ /home/user/Storyboarder-3.0.0-linux-x86_64.AppImage 
11:01:32.769 › Loading preferences from /home/user/.config/Storyboarder/pref.json
11:01:32.897 › Could not read prefs. Loading defaults.
11:01:32.897 › Error: ENOENT: no such file or directory, open '/home/user/.config/Storyboarder/pref.json'
    at Object.openSync (fs.js:466:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1812)
    at Object.readFileSync (fs.js:368:35)
    at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8583)
    at load (/tmp/.mount_Storyb9oqGpc/resources/app.asar/src/js/prefs.js:83:34)
    at Object.init (/tmp/.mount_Storyb9oqGpc/resources/app.asar/src/js/prefs.js:178:3)
    at Object.<anonymous> (/tmp/.mount_Storyb9oqGpc/resources/app.asar/src/js/main.js:13:12)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)

>(storyboarder:9015): Gtk-WARNING **: 11:01:36.912: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
(node:9015) UnhandledPromiseRejectionWarning: Could not find ffmpeg executable, tried "/tmp/.mount_Storyb9oqGpc/resources/app.asar/node_modules/@ffmpeg-installer/linux-x64/ffmpeg" and "/tmp/.mount_Storyb9oqGpc/resources/app.asar/node_modules/@ffmpeg-installer/ffmpeg/node_modules/@ffmpeg-installer/linux-x64/ffmpeg"
(node:9015) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9015) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

That said, I was able to successfully install storyboarder-appimage 2.0.1-1 via AUR trying to use the auto update function. The download works but the installation fails claiming a checksum mismatch.

![Screenshot_20210318_112215](https://user-images.githubusercontent.com/80885560/111602655-dc5f1480-87d3-11eb-9a0e-250b2c4ba3a3.png)

I tried changing the PKBUILD of the AUR-package to use https://github.com/wonderunit/storyboarder/releases/download/v3.0.0/Storyboarder-3.0.0-linux-x86_64.AppImage instead of https://github.com/wonderunit/storyboarder/releases/download/v2.0.1/Storyboarder-2.0.1-linux-x86_64.AppImage and determined the correct checksum for the file. The build was successful but running the program led to the original issue.

>11:32:42.559 › Loading preferences from /home/user/.config/Storyboarder/pref.json
11:32:42.670 › Could not read prefs. Loading defaults.
11:32:42.670 › Error: ENOENT: no such file or directory, open '/home/user/.config/Storyboarder/pref.json'
    at Object.openSync (fs.js:466:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1812)
    at Object.readFileSync (fs.js:368:35)
    at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8583)
    at load (/tmp/.mount_storybBtOWEW/resources/app.asar/src/js/prefs.js:83:34)
    at Object.init (/tmp/.mount_storybBtOWEW/resources/app.asar/src/js/prefs.js:178:3)
    at Object.<anonymous> (/tmp/.mount_storybBtOWEW/resources/app.asar/src/js/main.js:13:12)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)

>(storyboarder:17071): Gtk-WARNING **: 11:32:46.539: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
(node:17071) UnhandledPromiseRejectionWarning: Could not find ffmpeg executable, tried "/tmp/.mount_storybBtOWEW/resources/app.asar/node_modules/@ffmpeg-installer/linux-x64/ffmpeg" and "/tmp/.mount_storybBtOWEW/resources/app.asar/node_modules/@ffmpeg-installer/ffmpeg/node_modules/@ffmpeg-installer/linux-x64/ffmpeg"
(node:17071) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17071) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by droidoid** [comment]
### Fedora 33.
ffmpeg is installed
```
render@mamooth > ffmpeg -version
ffmpeg version 4.3.2 Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 10 (GCC)
configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --docdir=/usr/share/doc/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' --extra-ldflags='-Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld ' --extra-cflags=' -I/usr/include/rav1e' --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --disable-crystalhd --enable-fontconfig --enable-frei0r --enable-gcrypt --enable-gnutls --enable-ladspa --enable-libaom --enable-libdav1d --enable-libass --enable-libbluray --enable-libcdio --enable-libdrm --enable-libjack --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-liblensfun --enable-libmp3lame --enable-libmysofa --enable-nvenc --enable-openal --enable-opencl --enable-opengl --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librav1e --enable-libsmbclient --enable-version3 --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-version3 --enable-vapoursynth --enable-libvpx --enable-vulkan --enable-libglslang --enable-libx264 --enable-libx265 --enable-libxvid --enable-libxml2 --enable-libzimg --enable-libzvbi --enable-lv2 --enable-avfilter --enable-avresample --enable-libmodplug --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-lto --enable-libmfx --enable-runtime-cpudetect
libavutil      56. 51.100 / 56. 51.100
libavcodec     58. 91.100 / 58. 91.100
libavformat    58. 45.100 / 58. 45.100
libavdevice    58. 10.100 / 58. 10.100
libavfilter     7. 85.100 /  7. 85.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  7.100 /  5.  7.100
libswresample   3.  7.100 /  3.  7.100
libpostproc    55.  7.100 / 55.  7.100
```

But Storyboarder won`t start
```
render@mamooth ~/Downloads> ./Storyboarder-3.0.0-linux-x86_64.AppImage --no-sandbox
22:11:36.472 › Loading preferences from /home/render/.config/Storyboarder/pref.json
(node:150919) UnhandledPromiseRejectionWarning: Could not find ffmpeg executable, tried "/tmp/.mount_StorybORDdMZ/resources/app.asar/node_modules/@ffmpeg-installer/linux-x64/ffmpeg" and "/tmp/.mount_StorybORDdMZ/resources/app.asar/node_modules/@ffmpeg-installer/ffmpeg/node_modules/@ffmpeg-installer/linux-x64/ffmpeg"
(node:150919) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:150919) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by davidwpdlf** [comment]
I'm having the exact same problem on elementaryOS 5.1.7, but the .deb file is working perfectly.

**Comment by b4zz4** [comment]
It's compiled and worked well. It seems the problem is in some distributions and others not.

**Comment by opsaaaaa** [comment]
Same problem here on Pop!_OS 20.10 (Ubuntu).

**Comment by audionerd** [comment]
Looks like a problem with the ffmpeg installer we use (node-ffmpeg-installer), or a problem with the way we've configured it.

As a workaround, maybe it's possible to manually copy an ffmpeg binary into the Storyboarder AppImage where Storyboarder would expect it?

**Comment by bdkramer** [comment]
Getting the same/similar error attempting to launch Storyboarder-3.0.0-linux-x86_64.AppImage on Pop!_OS 20.10

Tried clearing the preferences folder, but that just resulted in messages about not having existing preferences. Notably, it doesn't get far enough to generate a new 'pref.json' file.

`puck% ./Storyboarder-3.0.0-linux-x86_64.AppImage 
03:23:26.492 › Loading preferences from /home/kramer/.config/Storyboarder/pref.json
03:23:26.599 › Could not read prefs. Loading defaults.
03:23:26.599 › Error: ENOENT: no such file or directory, open '/home/kramer/.config/Storyboarder/pref.json'
    at Object.openSync (fs.js:466:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1812)
    at Object.readFileSync (fs.js:368:35)
    at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8583)
    at load (/tmp/.mount_StorybGXnf6Y/resources/app.asar/src/js/prefs.js:83:34)
    at Object.init (/tmp/.mount_StorybGXnf6Y/resources/app.asar/src/js/prefs.js:178:3)
    at Object.<anonymous> (/tmp/.mount_StorybGXnf6Y/resources/app.asar/src/js/main.js:13:12)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
(node:192657) UnhandledPromiseRejectionWarning: Could not find ffmpeg executable, tried "/tmp/.mount_StorybGXnf6Y/resources/app.asar/node_modules/@ffmpeg-installer/linux-x64/ffmpeg" and "/tmp/.mount_StorybGXnf6Y/resources/app.asar/node_modules/@ffmpeg-installer/ffmpeg/node_modules/@ffmpeg-installer/linux-x64/ffmpeg"
(node:192657) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:192657) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

Processes simply hang after that last message, until ended with Ctrl+C

Extracting the Appimage reveals the existance of "squashfs-root/resources/app.asar.unpacked/node_modules/@ffmpeg-installer/darwin-x64/ffmpeg"

Attempting to execute that file results in the error:

`zsh: exec format error: ./ffmpeg
`

**Comment by ulfklose** [comment]
I'm having the same issue on Manjaro. ffmpeg is installed.

**Comment by gordielachance** [comment]
Same here on 
OS Linux Mint 19.3 Cinnamon
Kernel 5.0.0-32-generic

**Comment by maxtar** [comment]
Have the same problem.
Kubuntu 21.10.

**Comment by b3** [comment]
Same problem here on Debian Bullseye (11.2) and deb package not working (unable to install) as stated in #2336.

**Comment by JamesSolum** [comment]
Same problem on Fedora 35.
```
21:06:07.156 › Loading preferences from /home/jsolum/.config/Storyboarder/pref.json
21:06:07.345 › Could not read prefs. Loading defaults.
21:06:07.346 › Error: ENOENT: no such file or directory, open '/home/jsolum/.config/Storyboarder/pref.json'
    at Object.openSync (fs.js:466:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1812)
    at Object.readFileSync (fs.js:368:35)
    at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8583)
    at load (/tmp/.mount_StorybViCbvK/resources/app.asar/src/js/prefs.js:83:34)
    at Object.init (/tmp/.mount_StorybViCbvK/resources/app.asar/src/js/prefs.js:178:3)
    at Object.<anonymous> (/tmp/.mount_StorybViCbvK/resources/app.asar/src/js/main.js:13:12)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
(node:1148781) UnhandledPromiseRejectionWarning: Could not find ffmpeg executable, tried "/tmp/.mount_StorybViCbvK/resources/app.asar/node_modules/@ffmpeg-installer/linux-x64/ffmpeg" and "/tmp/.mount_StorybViCbvK/resources/app.asar/node_modules/@ffmpeg-installer/ffmpeg/node_modules/@ffmpeg-installer/linux-x64/ffmpeg"
(node:1148781) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1148781) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by AnonSchlingel** [comment]
Same Problem on Garuda Linux with Storyboarder-2.1.0-linux-x86_64.appimage.

`ffmpeg version n6.0 Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 13.1.1 (GCC) 20230429`
