### ISSUE TITLE
Shot Generator

### ISSUE THREAD

**Issue by CECIJANE** [wonderunit/storyboarder#2289]
Shot generator suddenly stopped working in my computer, I tried deleting and re-installing it, but it still does't work. I attached screenshots of storyboarder and what I see when I open the shot generator. 
![2021-09-17 (1)](https://user-images.githubusercontent.com/90934140/133848152-8193f933-779e-4890-8246-ed0845f3d827.png)
![2021-09-17](https://user-images.githubusercontent.com/90934140/133848153-e0cdc403-ec6a-4162-b285-7e8d1aed69a2.png)

**Comment by audionerd** [comment]
Do you see any errors listed in the log file?
Can show via `Help > Show Log File`

**Comment by CECIJANE** [comment]
> Do you see any errors listed in the log file?
> Can show via `Help > Show Log File`

Yes!!
[error] UnhandledRejection SyntaxError: Unexpected token   in JSON at position 0
    at JSON.parse (<anonymous>)
    at e.exports._loadFile (C:\Program Files\Storyboarder\resources\app.asar\src\build\shot-generator.js:11:91731)
    at new e.exports (C:\Program Files\Storyboarder\resources\app.asar\src\build\shot-generator.js:11:91587)
    at Object.initialize (C:\Program Files\Storyboarder\resources\app.asar\src\build\shot-generator.js:6:1498564)
    at C:\Program Files\Storyboarder\resources\app.asar\src\build\shot-generator.js:285:339473
    at Object.useMemo (C:\Program Files\Storyboarder\resources\app.asar\src\build\shot-generator.js:162:56550)
    at t.useMemo (C:\Program Files\Storyboarder\resources\app.asar\src\build\shot-generator.js:146:5984)
    at An (C:\Program Files\Storyboarder\resources\app.asar\src\build\shot-generator.js:285:339462)
    at C:\Program Files\Storyboarder\resources\app.asar\src\build\shot-generator.js:285:340147
    at Vi (C:\Program Files\Storyboarder\resources\app.asar\src\build\shot-generator.js:162:53011)

**Comment by Ranidu-M** [comment]
I am having the same issue. Is there a fix for this?
