### ISSUE TITLE
Storyboarder appimage does not start in Ubuntu 20.04

### ISSUE THREAD

**Issue by harmoniser** [wonderunit/storyboarder#2315]
I downloaded the latest release from your web site as an appimage, set it to executable and tried to run it on Ubuntu 20.04. Nothing happens. If I try to run it from the terminal I get as output: 

13:46:54.283 › Loading preferences from /home/per/.config/Storyboarder/pref.json
13:46:54.385 › Could not read prefs. Loading defaults.
13:46:54.386 › Error: ENOENT: no such file or directory, open '/home/per/.config/Storyboarder/pref.json'
    at Object.openSync (fs.js:466:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1812)
    at Object.readFileSync (fs.js:368:35)
    at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8583)
    at load (/tmp/.mount_StorybP2yxir/resources/app.asar/src/js/prefs.js:83:34)
    at Object.init (/tmp/.mount_StorybP2yxir/resources/app.asar/src/js/prefs.js:178:3)
    at Object.<anonymous> (/tmp/.mount_StorybP2yxir/resources/app.asar/src/js/main.js:13:12)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
(node:9313) UnhandledPromiseRejectionWarning: Could not find ffmpeg executable, tried "/tmp/.mount_StorybP2yxir/resources/app.asar/node_modules/@ffmpeg-installer/linux-x64/ffmpeg" and "/tmp/.mount_StorybP2yxir/resources/app.asar/node_modules/@ffmpeg-installer/ffmpeg/node_modules/@ffmpeg-installer/linux-x64/ffmpeg"
(node:9313) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9313) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

And there it stays, hung. 

Ffmpeg is installed on the system, and I even tried putting the executable in the same folder as Storyboarder but same result.

If there are certain dependencies and conditions required for running Storyboarder on Ubuntu 20.04 then please let us know. But it seems more like a bug because an Appimage should normally just run.

**Comment by lal0cura** [comment]
Hi, I have exacty the same Issue on ubuntu 20.04. I was wondering if someone have manage to run in correctly.   Thanks

**Comment by harmoniser** [comment]
Hi, I finally found a .deb version on github that worked.

It would have been nice if that one could be available at the download
site. Took a while to find it.

Here it is: https://github.com/wonderunit/storyboarder/releases/

**Comment by DominikNovosel** [comment]
Similar situation here:

Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.11.0-46-generic
OS Type: 64-bit
Processors: 4 × Intel® Core™ i5-3230M CPU @ 2.60GHz
Memory: 7.6 GiB of RAM

23:21:31.101 › Loading preferences from /home/korisnik/.config/Storyboarder/pref.json
23:21:31.249 › Could not read prefs. Loading defaults.
23:21:31.250 › Error: ENOENT: no such file or directory, open '/home/korisnik/.config/Storyboarder/pref.json'
    at Object.openSync (fs.js:466:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1812)
    at Object.readFileSync (fs.js:368:35)
    at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8583)
    at load (/tmp/.mount_StorybX3UDYl/resources/app.asar/src/js/prefs.js:83:34)
    at Object.init (/tmp/.mount_StorybX3UDYl/resources/app.asar/src/js/prefs.js:178:3)
    at Object.<anonymous> (/tmp/.mount_StorybX3UDYl/resources/app.asar/src/js/main.js:13:12)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
(node:29017) UnhandledPromiseRejectionWarning: Could not find ffmpeg executable, tried "/tmp/.mount_StorybX3UDYl/resources/app.asar/node_modules/@ffmpeg-installer/linux-x64/ffmpeg" and "/tmp/.mount_StorybX3UDYl/resources/app.asar/node_modules/@ffmpeg-installer/ffmpeg/node_modules/@ffmpeg-installer/linux-x64/ffmpeg"
(node:29017) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:29017) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I hope this is handled soon because installing stuff from .deb is kinda awkward.

**Comment by DominikNovosel** [comment]
Update: for whatever it's worth, observing the console when running Storyboarder installed from .deb (which actually works) reveals a similar set of errors, and i don't think ffmpeg itself has much to do with the actual issue. The next most likely suspects are probably Electron and Node.js, or the app itself. Please keep in mind that these particular technologies and in fact, software development as a whole are a tad out of my comfort zone at the moment and I may be completely wrong here.

~$ storyboarder
22:25:56.815 › Loading preferences from /home/korisnik/.config/Storyboarder/pref.json
22:25:57.934 › ffmpeg version N-87327-g18821e3ba1-static
22:25:57.938 › Reading /home/korisnik/.config/Storyboarder/keymap.json
22:25:57.956 › No license key found
22:25:58.010 › http://192.168.3.6:1888
(node:47584) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
(node:47584) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
22:25:58.849 › Checking for update
22:25:58.850 › auto-updater: checking-for-update
22:25:58.988 › Error: Error: ENOENT: no such file or directory, open '/opt/Storyboarder/resources/app-update.yml'
22:25:58.989 › auto-updater: error Error: ENOENT: no such file or directory, open '/opt/Storyboarder/resources/app-update.yml'
[Error: ENOENT: no such file or directory, open '/opt/Storyboarder/resources/app-update.yml'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/opt/Storyboarder/resources/app-update.yml'
}
(node:47584) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/opt/Storyboarder/resources/app-update.yml'
(node:47584) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:47584) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by damascene** [comment]
Same here, unable to start the Appimage. Also snap require a signature. Could you fix and upload the snap version to snapcraft so it will be easier to install on most linux systems? 

Thank you

**Comment by Regular-Baf** [comment]
I've had these same issues on Fedora when trying to use the AppImage. The snap also doesn't work (with snapd installed), and the `.deb` build won't install with alien. Personally, I'd really like to see this app as a flatpak on Flathub.

**Comment by Regular-Baf** [comment]
For those interested, I have built an unofficial Flatpak for Storyboarder that I can confirm works. At least it does on Fedora 35.
https://github.com/Regular-Baf/Bafpak/releases/tag/Unofficial-Flatpak
