### ISSUE TITLE
appimage 3.0.0 not work in my debian bullseye

### ISSUE THREAD

**Issue by quirinux-so** [wonderunit/storyboarder#2319]
Appimage not work in Debian Bullseye.

Terminal: 

$ **./Storyboarder-3.0.0-linux-x86_64.AppImage** 
19:55:33.596 › Loading preferences from /home/charlie/.config/Storyboarder/pref.json
19:55:33.730 › Could not read prefs. Loading defaults.
19:55:33.731 › Error: ENOENT: no such file or directory, open '/home/charlie/.config/Storyboarder/pref.json'
    at Object.openSync (fs.js:466:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1812)
    at Object.readFileSync (fs.js:368:35)
    at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8583)
    at load (/tmp/.mount_StorybUxOKt5/resources/app.asar/src/js/prefs.js:83:34)
    at Object.init (/tmp/.mount_StorybUxOKt5/resources/app.asar/src/js/prefs.js:178:3)
    at Object.<anonymous> (/tmp/.mount_StorybUxOKt5/resources/app.asar/src/js/main.js:13:12)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
(node:8634) UnhandledPromiseRejectionWarning: Could not find ffmpeg executable, tried "/tmp/.mount_StorybUxOKt5/resources/app.asar/node_modules/@ffmpeg-installer/linux-x64/ffmpeg" and "/tmp/.mount_StorybUxOKt5/resources/app.asar/node_modules/@ffmpeg-installer/ffmpeg/node_modules/@ffmpeg-installer/linux-x64/ffmpeg"
(node:8634) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8634) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Intel i5 8GB RAM 
SSD
Intel HD Graphics
Debian Bullseye

**Comment by quirinux-so** [comment]
This deb package work's for me! 
https://github.com/wonderunit/storyboarder/releases/tag/v3.0.0

**Comment by b3** [comment]
Can you describe your environment? I am unable to install the deb package as stated in #2336.

**Comment by 0x0000beef** [comment]
appimage 3.0.0 will not work at all bc ffmpeg from macos was mistakenly inserted into it. 

here is a quick rebuild with an actual library: https://disk.yandex.ru/d/XCmDSc6eCq97cA
