### ISSUE TITLE
unable to start the linux appimage build

### ISSUE THREAD

**Issue by shi-yan** [wonderunit/storyboarder#2340]
**Describe the bug**
saw the following error when running the appimage build:

```bash
shiy@shiy-desktop:~/Downloads$ ./Storyboarder-3.0.0-linux-x86_64.AppImage 
18:31:53.264 › Loading preferences from /home/shiy/.config/Storyboarder/pref.json
18:31:53.331 › Could not read prefs. Loading defaults.
18:31:53.331 › Error: ENOENT: no such file or directory, open '/home/shiy/.config/Storyboarder/pref.json'
    at Object.openSync (fs.js:466:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1812)
    at Object.readFileSync (fs.js:368:35)
    at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8583)
    at load (/tmp/.mount_StorybDNkYTZ/resources/app.asar/src/js/prefs.js:83:34)
    at Object.init (/tmp/.mount_StorybDNkYTZ/resources/app.asar/src/js/prefs.js:178:3)
    at Object.<anonymous> (/tmp/.mount_StorybDNkYTZ/resources/app.asar/src/js/main.js:13:12)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
(node:30216) UnhandledPromiseRejectionWarning: Could not find ffmpeg executable, tried "/tmp/.mount_StorybDNkYTZ/resources/app.asar/node_modules/@ffmpeg-installer/linux-x64/ffmpeg" and "/tmp/.mount_StorybDNkYTZ/resources/app.asar/node_modules/@ffmpeg-installer/ffmpeg/node_modules/@ffmpeg-installer/linux-x64/ffmpeg"
(node:30216) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:30216) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


```
I have ffmpeg installed via apt, so the cmd ffmpeg is available.
**To Reproduce**
1. Go to the github release page, download the latest appimage
2. try to start it on ubuntu 20.04

**Expected behavior**
app can start. but won't start, complaining about missing ffmpeg and unable to open pref.json

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04
 - Browser chrome
 - Version 3.0.0

**Comment by drautb** [comment]
Looks like a duplicate of https://github.com/wonderunit/storyboarder/issues/2315
