### ISSUE TITLE
Tried to run the appimage but it doesn't work.

### ISSUE THREAD

**Issue by noelcurray** [wonderunit/storyboarder#2366]

**Comment by JuPlutonic** [comment]
### Version 2.1.0
size 125M
sha256 aa068c49665ba72a9177351a3bf1c1ed15262c0481854f462cf4e556767b8b32
`http://192.168.31.206:1888` - opens
UI - opens

### Version 3.0.0
size 134M
sha256 807942c6420ad745f66978863ecf7e4369ca32b560ece9159c6652401025edef
`http://192.168.31.206:1888` - didn't open
UI - didn't open
Errors about ffmpeg, while the application hangs or freezes:

```
22:28:32.113 › Loading preferences from /home/alessio/.config/Storyboarder/pref.json
22:28:32.275 › Could not read prefs. Loading defaults.
22:28:32.276 › Error: ENOENT: no such file or directory, open '/home/NNN/.config/Storyboarder/pref.json'
    at Object.openSync (fs.js:466:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1812)
    at Object.readFileSync (fs.js:368:35)
    at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8583)
    at load (/tmp/.mount_StorybVlInyJ/resources/app.asar/src/js/prefs.js:83:34)
    at Object.init (/tmp/.mount_StorybVlInyJ/resources/app.asar/src/js/prefs.js:178:3)
    at Object.<anonymous> (/tmp/.mount_StorybVlInyJ/resources/app.asar/src/js/main.js:13:12)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
(node:15979) UnhandledPromiseRejectionWarning: Could not find ffmpeg executable, tried "/tmp/.mount_StorybVlInyJ/resources/app.asar/node_modules/@ffmpeg-installer/linux-x64/ffmpeg" and "/tmp/.mount_StorybVlInyJ/resources/app.asar/node_modules/@ffmpeg-installer/ffmpeg/node_modules/@ffmpeg-installer/linux-x64/ffmpeg"
(node:15979) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15979) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
### To Reproduce
```sh
chmod u+x Storyboarder-X.X.0-linux-x86_64.AppImage
./Storyboarder-X.X.0-linux-x86_64.AppImage
```
### Expected behavior
 as in 2.1.0:

 - no ffmpeg error during launch from console
 - and app launches, doesn't freezes


### Desktop
`Linux 5.4.0-125-generic #141~18.04.1-Ubuntu` SMP x86_64 GNU/Linux
