### ISSUE TITLE
AppImage not opening

### ISSUE THREAD

**Issue by AbidingMonkey** [wonderunit/storyboarder#2369]
Just downloaded the AppImage on Kubuntu 22.04. App does not open. Opened in the terminal. This is the log.

![image](https://user-images.githubusercontent.com/68205720/180096381-06d5ddbb-e6af-47f8-986a-2ca3a1026429.png)

**Comment by arkanoid87** [comment]
same problem here
Ubuntu 22.04

```
./Storyboarder-3.0.0-linux-x86_64.AppImage 
20:06:21.998 › Loading preferences from /home/jack/.config/Storyboarder/pref.json
20:06:22.073 › Could not read prefs. Loading defaults.
20:06:22.074 › Error: ENOENT: no such file or directory, open '/home/jack/.config/Storyboarder/pref.json'
    at Object.openSync (fs.js:466:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1812)
    at Object.readFileSync (fs.js:368:35)
    at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8583)
    at load (/tmp/.mount_StorybjGg5CT/resources/app.asar/src/js/prefs.js:83:34)
    at Object.init (/tmp/.mount_StorybjGg5CT/resources/app.asar/src/js/prefs.js:178:3)
    at Object.<anonymous> (/tmp/.mount_StorybjGg5CT/resources/app.asar/src/js/main.js:13:12)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
(node:621310) UnhandledPromiseRejectionWarning: Could not find ffmpeg executable, tried "/tmp/.mount_StorybjGg5CT/resources/app.asar/node_modules/@ffmpeg-installer/linux-x64/ffmpeg" and "/tmp/.mount_StorybjGg5CT/resources/app.asar/node_modules/@ffmpeg-installer/ffmpeg/node_modules/@ffmpeg-installer/linux-x64/ffmpeg"
(node:621310) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:621310) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ghost** [comment]
Same problem as well
Fedora 37

```
00:00:00.000 › Loading preferences from /home/USERNAME/.config/Storyboarder/pref.json
00:00:00.000 › Could not read prefs. Loading defaults.
00:00:00.000 › Error: ENOENT: no such file or directory, open '/home/USERNAME/.config/Storyboarder/pref.json'
    at Object.openSync (fs.js:466:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1812)
    at Object.readFileSync (fs.js:368:35)
    at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8583)
    at load (/tmp/.mount_StorybgHmj6A/resources/app.asar/src/js/prefs.js:83:34)
    at Object.init (/tmp/.mount_StorybgHmj6A/resources/app.asar/src/js/prefs.js:178:3)
    at Object.<anonymous> (/tmp/.mount_StorybgHmj6A/resources/app.asar/src/js/main.js:13:12)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
(node:95940) UnhandledPromiseRejectionWarning: Could not find ffmpeg executable, tried "/tmp/.mount_StorybgHmj6A/resources/app.asar/node_modules/@ffmpeg-installer/linux-x64/ffmpeg" and "/tmp/.mount_StorybgHmj6A/resources/app.asar/node_modules/@ffmpeg-installer/ffmpeg/node_modules/@ffmpeg-installer/linux-x64/ffmpeg"
(node:95940) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:95940) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Appimage 2.1.0 is also broken, for fedora 37 at least. Mentioned the details here:
https://github.com/wonderunit/storyboarder/issues/2108
