### ISSUE TITLE
Can't Start or open any projects

### ISSUE THREAD

**Issue by JoelTBerg** [wonderunit/storyboarder#2412]
**Describe the bug**
I just got storyboarder and I opened it to try mess with it and start using it, but when I go to try and make any new project or open a fountain script or anything at all, it just gives me an error and does nothing.

**Expected behavior**
I want to open the file, or create a new file. Also, what is the file extension of new files?

**Screenshots**
![image](https://user-images.githubusercontent.com/112780834/214309309-450948b5-d91f-454e-9b55-b65241d9dab1.png)

**Desktop (please complete the following information):**
 - Linux Mint Cinnamon 21
 - Storyboarder 2.1.0 Linux appimage

**Comment by spaceclottey** [comment]
I also have this issue

**Comment by BWelygan** [comment]
Same here. 
If I extract the appimage and run from CLI i get this error:

Attempt 1: 
(node:1201241) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
    at Object.mkdirSync (fs.js:770:3)
    at createAndLoadScene (/home/helliouse/Downloads/squashfs-root/resources/app.asar/src/js/main.js:881:6)
(node:1201241) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1201241) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Attempt 2:
(node:1201241) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
    at Object.mkdirSync (fs.js:770:3)
    at createAndLoadScene (/home/helliouse/Downloads/squashfs-root/resources/app.asar/src/js/main.js:881:6)
(node:1201241) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
