### ISSUE TITLE
Errors attempting to open the program -> cannot run

### ISSUE THREAD

**Issue by The-Maize** [wonderunit/storyboarder#2463]
**Describe the bug**
[m@fedora Appimages]$ ./Storyboarder-2.1.0-linux-x86_64.AppImage 
22:14:59.697 › Loading preferences from /home/m/.config/Storyboarder/pref.json
22:14:59.761 › Could not read prefs. Loading defaults.
22:14:59.762 › Error: ENOENT: no such file or directory, open '/home/m/.config/Storyboarder/pref.json'
    at Object.openSync (fs.js:453:3)
    at Object.func [as openSync] (electron/js2c/asar.js:155:31)
    at Object.readFileSync (fs.js:353:35)
    at Object.fs.readFileSync (electron/js2c/asar.js:597:40)
    at load (/tmp/.mount_StorybAK6glI/resources/app.asar/src/js/prefs.js:83:34)
    at Object.init (/tmp/.mount_StorybAK6glI/resources/app.asar/src/js/prefs.js:178:3)
    at Object.<anonymous> (/tmp/.mount_StorybAK6glI/resources/app.asar/src/js/main.js:12:12)
    at Module._compile (internal/modules/cjs/loader.js:839:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:851:10)
    at Module.load (internal/modules/cjs/loader.js:701:32)
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
22:15:16.091 › ffmpeg version N-87327-g18821e3ba1-static
22:15:16.092 › Reading /home/m/.config/Storyboarder/keymap.json
22:15:16.160 › No license key found
22:15:17.927 › http://192.168.1.132:1888
[30325:0629/221531.298892:FATAL:gpu_data_manager_impl_private.cc(892)] The display compositor is frequently crashing. Goodbye.
Trace/breakpoint trap (core dumped)
.
**To Reproduce**
1. Run the program in cmdl on Fedora 38 KDE 
2. See error

Does not run in any form, cmdl or gui launch

**Expected behavior**
to run

Desktop
- Fedora Linux 38 (KDE Plasma) x86_64 
- Kernel: 6.3.8-200.fc38.x86_64 
- Kernel: 6.3.8-200.fc38.x86_64 
- CPU: AMD Ryzen 7 1700X (16) @ 3.400GHz 
- GPU: NVIDIA GeForce GTX 1080  -- Driver 535.54.03     |    Cuda driver 12.2
- Memory: 5945MiB / 31997MiB 

Attempted to run also via extracted app image, failed as well same issues. 
My compositor is not crashing as it is saying. dmesg jctl all confirm this is not the case. 
Drivers are late and not having any issues with any other program, nor am i seeing any logs to support it. 
System is stable otherwise.

**Comment by The-Maize** [comment]
it is the same issue with characterizer as well just for the added note.

**Comment by henryContreras** [comment]
The same happens on Ubuntu. 22.04.2 LTS

AppImage

18:06:40.094 › Loading preferences from ~/.config/Storyboarder/pref.json
18:06:40.219 › Could not read prefs. Loading defaults.
18:06:40.220 › Error: ENOENT: no such file or directory, open '~/.config/Storyboarder/pref.json'
    at Object.openSync (fs.js:453:3)
    at Object.func [as openSync] (electron/js2c/asar.js:155:31)
    at Object.readFileSync (fs.js:353:35)
    at Object.fs.readFileSync (electron/js2c/asar.js:597:40)
    at load (/tmp/.mount_Storybzaojzn/resources/app.asar/src/js/prefs.js:83:34)
    at Object.init (/tmp/.mount_Storybzaojzn/resources/app.asar/src/js/prefs.js:178:3)
    at Object.<anonymous> (/tmp/.mount_Storybzaojzn/resources/app.asar/src/js/main.js:12:12)
    at Module._compile (internal/modules/cjs/loader.js:839:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:851:10)
    at Module.load (internal/modules/cjs/loader.js:701:32)
18:07:13.815 › ffmpeg version N-87327-g18821e3ba1-static
18:07:13.816 › Reading ~/.config/Storyboarder/keymap.json
18:07:13.945 › No license key found
18:07:17.286 › http://192.168.68.112:1888
[14486:0801/180741.809446:FATAL:gpu_data_manager_impl_private.cc(892)] The display compositor is frequently crashing. Goodbye.
Trace/breakpoint trap (core dumped)

deb

18:13:43.248 › Loading preferences from ~/.config/Storyboarder/pref.json
18:13:43.256 › Could not read prefs. Loading defaults.
18:13:43.257 › Error: ENOENT: no such file or directory, open '~/.config/Storyboarder/pref.json'
    at Object.openSync (fs.js:466:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1812)
    at Object.readFileSync (fs.js:368:35)
    at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8583)
    at load (/opt/Storyboarder/resources/app.asar/src/js/prefs.js:83:34)
    at Object.init (/opt/Storyboarder/resources/app.asar/src/js/prefs.js:178:3)
    at Object.<anonymous> (/opt/Storyboarder/resources/app.asar/src/js/main.js:13:12)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
18:13:43.801 › ffmpeg version N-87327-g18821e3ba1-static
18:13:43.806 › Reading ~/.config/Storyboarder/keymap.json
18:13:43.825 › No license key found
18:13:43.861 › http://192.168.68.112:1888
(node:19163) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
(node:19163) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
[19163:0801/181347.132149:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)

Snap

error: cannot find signatures with metadata for snap "./Storyboarder-3.0.0-linux-amd64.snap"

System info: neofetch

            .-/+oossssoo+/-.                
        `:+ssssssssssssssssss+:`           ------------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 22.04.2 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: Stealth 15M A11SEK REV:1.0 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.19.0-46-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 26 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 2910 (dpkg), 50 (flatpak), 24 (snap) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.1.16 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1920x1080 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: GNOME 42.9 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: Adwaita 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Yaru-red-dark [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: Yaru-red [GTK2/3] 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: guake 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: 11th Gen Intel i7-1185G7 (8) @ 4.800GHz 
    .ossssssssssssssssssdMMMNysssso.       GPU: Intel TigerLake-LP GT2 [Iris Xe Graphics] 
      -+sssssssssssssssssyyyssss+-         GPU: NVIDIA GeForce RTX 2060 Max-Q 
        `:+ssssssssssssssssss+:`           Memory: 4986MiB / 15691MiB 
            .-/+oossssoo+/-.

**Comment by The-Maize** [comment]
for you it might be a matter of the switching graphics being an issue. i havent got a work around for mine yet, but i have seen others with laptops that have a have 2 sources of graphics. Also i did attempt to extract the appimage and ran it with sudo, it was able to run, BUT.... i couldnt do anything due to the lag. it was still not detecting my single card (1080), that said i have a single gpu (3080 ) laptop that had zero issues with this app. so it leads tme to believe it could also be an environment thing or a app image permission thing. Ill do some more troubleshooting at some point (i had forgotten about it to be fair.) and will re investigate some point soon

**Comment by The-Maize** [comment]
21:36:21.357 › Loading preferences from /home/user/.config/Storyboarder/pref.json
21:36:21.361 › Could not read prefs. Loading defaults.
21:36:21.361 › Error: ENOENT: no such file or directory, open '/home/user/.config/Storyboarder/pref.json'
    at Object.openSync (fs.js:466:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1812)
    at Object.readFileSync (fs.js:368:35)
    at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8583)
    at load (/home/user/.local/share/applications/AppImages/squashfs-root/resources/app.asar/src/js/prefs.js:83:34)
    at Object.init (/home/user/.local/share/applications/AppImages/squashfs-root/resources/app.asar/src/js/prefs.js:178:3)
    at Object.<anonymous> (/home/user/.local/share/applications/AppImages/squashfs-root/resources/app.asar/src/js/main.js:13:12)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
(node:1574972) UnhandledPromiseRejectionWarning: Could not find ffmpeg executable, tried "/home/user/.local/share/applications/AppImages/squashfs-root/resources/app.asar/node_modules/@ffmpeg-installer/linux-x64/ffmpeg" and "/home/user/.local/share/applications/AppImages/squashfs-root/resources/app.asar/node_modules/@ffmpeg-installer/ffmpeg/node_modules/@ffmpeg-installer/linux-x64/ffmpeg"
(node:1574972) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1574972) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[1574972:1003/213621.888997:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap

I can confirm its not a switchable graphics thing, as i dont have that technology present. 

but i am still getting some errors on ubuntu.

**Comment by The-Maize** [comment]
Error is still present with both the Deb file, the RPM and the Appimage.

Ran tests on:
22.04
+
fedora 38

**Comment by sleeplessKomodo** [comment]
Error still present on fedora 39, Appimage. Glad to know there are options to upgrade before I can see the program operate. 

Is it possible to run the server on a local bare metal? I will try and figure this out, because it seems like an Nvidia + Wayland issue. 

```
Operating System: Nobara (Fedora) Linux 39
KDE Plasma Version: 6.0.5
KDE Frameworks Version: 6.2.0
Qt Version: 6.6.2
Kernel Version: 6.8.12-200.fsync.fc39.x86_64 (64-bit)
Graphics Platform: Wayland
Graphics Processor: NVIDIA GeForce RTX 2080 SUPER/PCIe/SSE2
```

```
10:38:23.926 › Could not read prefs. Loading defaults.
10:38:23.927 › Error: ENOENT: no such file or directory, open '/home/jimbo/.config/Storyboarder/pref.json'
    at Object.openSync (fs.js:453:3)
    at Object.func [as openSync] (electron/js2c/asar.js:155:31)
    at Object.readFileSync (fs.js:353:35)
    at Object.fs.readFileSync (electron/js2c/asar.js:597:40)
    at load (/tmp/.mount_StorybEP0UYx/resources/app.asar/src/js/prefs.js:83:34)
    at Object.init (/tmp/.mount_StorybEP0UYx/resources/app.asar/src/js/prefs.js:178:3)
    at Object.<anonymous> (/tmp/.mount_StorybEP0UYx/resources/app.asar/src/js/main.js:12:12)
    at Module._compile (internal/modules/cjs/loader.js:839:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:851:10)
    at Module.load (internal/modules/cjs/loader.js:701:32)
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
10:38:29.563 › ffmpeg version N-87327-g18821e3ba1-static
10:38:29.564 › Reading /home/jimbo/.config/Storyboarder/keymap.json
10:38:29.631 › No license key found
10:38:29.670 › http://192.168.0.205:1888
[48511:0613/103834.674556:FATAL:gpu_data_manager_impl_private.cc(892)] The display compositor is frequently crashing. Goodbye.
Trace/breakpoint trap (core dumped)
```

**Comment by Nezarik-Intmax** [comment]
Same error

$ ./Storyboarder-2.1.0-linux-x86_64.AppImage 
08:58:02.908 › Loading preferences from /home/maxim/.config/Storyboarder/pref.json
08:58:02.978 › Could not read prefs. Loading defaults.
08:58:02.979 › Error: ENOENT: no such file or directory, open '/home/maxim/.config/Storyboarder/pref.json'
    at Object.openSync (fs.js:453:3)
    at Object.func [as openSync] (electron/js2c/asar.js:155:31)
    at Object.readFileSync (fs.js:353:35)
    at Object.fs.readFileSync (electron/js2c/asar.js:597:40)
    at load (/tmp/.mount_StorybwQ2SWg/resources/app.asar/src/js/prefs.js:83:34)
    at Object.init (/tmp/.mount_StorybwQ2SWg/resources/app.asar/src/js/prefs.js:178:3)
    at Object.<anonymous> (/tmp/.mount_StorybwQ2SWg/resources/app.asar/src/js/main.js:12:12)
    at Module._compile (internal/modules/cjs/loader.js:839:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:851:10)
    at Module.load (internal/modules/cjs/loader.js:701:32)
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
08:58:19.113 › ffmpeg version N-87327-g18821e3ba1-static
08:58:19.114 › Reading /home/maxim/.config/Storyboarder/keymap.json
08:58:19.184 › No license key found
08:58:20.880 › http://192.168.1.102:1888
[17846:1219/085833.903129:FATAL:gpu_data_manager_impl_private.cc(892)] The display compositor is frequently crashing. Goodbye.

***

./Storyboarder-3.0.0-linux-x86_64.AppImage 
09:09:28.234 › Loading preferences from /home/maxim/.config/Storyboarder/pref.json
09:09:28.329 › Could not read prefs. Loading defaults.
09:09:28.330 › SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at load (/tmp/.mount_StorybxrVKXN/resources/app.asar/src/js/prefs.js:83:25)
    at Object.init (/tmp/.mount_StorybxrVKXN/resources/app.asar/src/js/prefs.js:178:3)
    at Object.<anonymous> (/tmp/.mount_StorybxrVKXN/resources/app.asar/src/js/main.js:13:12)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Object.<anonymous> (electron/js2c/browser_init.js:185:3510)
(node:20818) UnhandledPromiseRejectionWarning: Could not find ffmpeg executable, tried "/tmp/.mount_StorybxrVKXN/resources/app.asar/node_modules/@ffmpeg-installer/linux-x64/ffmpeg" and "/tmp/.mount_StorybxrVKXN/resources/app.asar/node_modules/@ffmpeg-installer/ffmpeg/node_modules/@ffmpeg-installer/linux-x64/ffmpeg"
(node:20818) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20818) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[20818:1219/090947.506110:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.


***
System info:
OS: Arch Linux 
Host: B450 AORUS M 
Kernel: 6.6.65-1-lts 
Shell: bash 5.2.37 
Resolution: 1920x1080, 2560x1440 
DE: Plasma 6.2.4 
CPU: AMD Ryzen 7 2700 (16) @ 3.200GHz 
GPU: NVIDIA GeForce RTX 2060 SUPER 
Memory: 12910MiB / 48120MiB 

***
Btw: Windows version via Wine have some icons issue but works fine in general
