### ISSUE TITLE
ffmpeg.exe ENOENT

### ISSUE THREAD

**Issue by Nualie** [wonderunit/storyboarder#2527]
Log file:

[2024-04-07 01:19:04.092] [error] Error: spawn C:\Program Files\Storyboarder\resources\app.asar\node_modules\@ffmpeg-installer\win32-x64\ffmpeg.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

There's ffmpeg.exe at "C:\Program Files\Storyboarder\resources\app.asar.unpacked\node_modules\@ffmpeg-installer\win32-x64" though
Didn't have this issue on my previous computer's install :(

**Comment by Nualie** [comment]
Issue seems fixed in 3.0 pre-release
