### ISSUE TITLE
Error opening script-based projects

### ISSUE THREAD

**Issue by audionerd** [wonderunit/storyboarder#416]
From "Recent Documents" or just with "Open", I get:

```
Uncaught Exception:
TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1355:5)
    at loadStoryboarderWindow (~/storyboarder/src/js/main.js:449:17)
    at fs.readFile (~/storyboarder/src/js/main.js:219:9)
    at tryToString (fs.js:449:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
```

**Comment by setpixel** [comment]
fixed!
