### ISSUE TITLE
Last board can not be duplicated

### ISSUE THREAD

**Issue by flipswitchingmonkey** [wonderunit/storyboarder#673]
Create any number of boards
Select last board
Duplicate
Error: could not duplicate board

Win 10, 0.12.1

**Comment by audionerd** [comment]
When you get this error, what does the console log say?

You can find the console log by selecting "View > Toggle Developer Tools" and looking at the "Console" tab. 
We'd need the last few log traces around the time this error occurs in order to debug, so you might need to scroll down in the log to see them.

**Comment by flipswitchingmonkey** [comment]
```
C:\Program Files\Storyboarder\resources\app.asar\src\js\window\main-window.js:1705 Error: ENOENT: no such file or directory, open 'C:\Users\xxx\Desktop\test2\images\board-3-1W02I.png'
    at Object.fs.openSync (fs.js:652:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:553:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:505:29)
    at saveImageFile.then (C:\Program Files\Storyboarder\resources\app.asar\src\js\window\main-window.js:1685:33)
    at <anonymous>
```
Indeed the png is not being created for the last frame, only for the previous ones:
```
15/09/2017  18:20           120,475 board-1-RM4AI-reference.png
15/09/2017  18:20             2,952 board-1-RM4AI-thumbnail.png
15/09/2017  18:20            27,176 board-1-RM4AI.png
15/09/2017  18:20           162,363 board-2-6J69M-reference.png
15/09/2017  18:20               764 board-2-6J69M-thumbnail.png
15/09/2017  18:20            27,176 board-2-6J69M.png
15/09/2017  18:24           112,618 board-3-1W02I-reference.png
15/09/2017  18:24             2,878 board-3-1W02I-thumbnail.png
```

**Comment by audionerd** [comment]
Could you paste more of the log for context?

**Comment by audionerd** [comment]
Odd. I'm not sure what would cause the main board image to not be created, but the reference and thumbnail were.
I haven't been able to recreate this issue yet.
